// Localize Strings for English Ability Simulator for JP Servers


const Locale = {
    group0: "Other",
    group1: "Stat Enhancement",
    group2: "Stat Enhancement (Lesser)",
    group3: "Stat Enhancement (Special/1)",
    group4: "Stat Enhancement (Special/2)",
    group5: "Special Ability Factor",
    group6: "Resistance",
    group7: "Status Effect",
    group8: "Soul",
    group9: "Fever",
    group10: "Ripper/Slayer",
    group11: "Receptors",
    group12: "Special",
    group13: "S-Class Special Ability (Placeholder)",
    group21: "S-Class Special Ability Factor",
    group22: "Special Effect",
    group23: "Catalyst",
    specialAbility: "Special Ability",
    ability: "Ability",
    selectAbility: "Select Abilities",
    campaign_satk5: "5% Strike UP",
    campaign_ratk5: "5% Shoot UP",
    campaign_tatk5: "5% Tech UP",
    campaign_hppp5: "5% HP&PP UP",
    campaign_special5: "5% Special UP",
    satk: "S-ATK",
    ratk: "R-ATK",
    tatk: "T-ATK",
    sdef: "S-DEF",
    rdef: "R-DEF",
    tdef: "T-DEF",
    dex: "DEX",
    hp: "HP",
    pp: "PP",
    strikeResist: "Strike Resist",
    rangeResist: "Range Resist",
    techResist: "Tech Resist",
    fireResist: "Fire Resist",
    iceResist: "Ice Resist",
    ltnResist: "Lightning Resist",
    windResist: "Wind Resist",
    lightResist: "Light Resist",
    darkResist: "Dark Resist"
}