// Localize Strings for English Ability Simulator for JP Servers


const Locale = {
    group0:"Other",
    group1:"Stat Enhancement",
    group2:"Stat Enhancement (Lesser)",
    group3:"Stat Enhancement (Special/1)",
    group4:"Stat Enhancement (Special/2)",
    group5:"Special Ability Factor",
    group6:"Resistance",
    group7:"Status Effect",
    group8:"Soul",
    group9:"Fever",
    group10:"Ripper/Slayer",
    group11:"Receptors",
    group12:"Special",
    group13:"S-Grade Augment 1 (Weapon)",
    group14:"S-Grade Augment 2 (Weapon)",
    group15:"S-Grade Augment 3 (Weapon)",
    group16:"S-Grade Augment 4 (Weapon)",
    group17:"S-Grade Augment 5 (Weapon)",
    group18:"S-Grade Augment 6 (Rear Unit)",
    group19:"S-Grade Augment 7 (Arm Unit)",
    group20:"S-Grade Augment 8 (Leg Unit)",
    group21:"Special S-Grade Augment Factor",
    group22:"Special Effect",
    group23:"Catalyst",
    specialAbility:"Augment",
    ability:"Ability",
    selectAbility:"Select Abilities",
    campaign_satk5:"5% Melee UP",
    campaign_ratk5:"5% Range UP",
    campaign_tatk5:"5% Tech UP",
    campaign_hppp5:"5% HPPP UP",
    campaign_special5:"5% Special UP",
    satk:"MEL Pwr",
    ratk:"RNG Pwr",
    tatk:"TEC Pwr",
    sdef:"MEL Def",
    rdef:"RNG Def",
    tdef:"TEC Def",
    dex:"DEX",
    hp:"HP",
    pp:"PP",
    strikeResist:"Melee Resist",
    rangeResist:"Ranged Resist",
    techResist:"Tech Resist", 
    fireResist:"Fire Resist", 
    iceResist:"Ice Resist", 
    ltnResist:"Lightning Resist",
    windResist:"Wind Resist",
    lightResist:"Light Resist",
    darkResist:"Dark Resist"
}