// Localize Strings for English Ability Simulator for JP Servers


const Locale = {
    group0:"Other",
    group1:"Stat Enhancement",
    group2:"Stat Enhancement (Lesser)",
    group3:"Stat Enhancement (Special/1)",
    group4:"Stat Enhancement (Special/2)",
    group5:"Special Ability Factor",
    group6:"Resistance",
    group7:"Status Effect",
    group8:"Soul",
    group9:"Fever",
    group10:"Ripper/Slayer",
    group11:"Receptors",
    group12:"Special",
    group13:"S-Class Special Ability 1 (Weapon)",
    group14:"S-Class Special Ability 2 (Weapon)",
    group15:"S-Class Special Ability 3 (Weapon)",
    group16:"S-Class Special Ability 4 (Weapon)",
    group17:"S-Class Special Ability 5 (Weapon)",
    group18:"S-Class Special Ability 6 (Rear Unit)",
    group19:"S-Class Special Ability 7 (Arm Unit)",
    group20:"S-Class Special Ability 8 (Leg Unit)",
    group21:"S-Class Special Ability Factor",
    specialAbility:"Augment",
    ability:"Ability",
    selectAbility:"Select Abilities",
    campaign_satk5:"5% Strike UP",
    campaign_ratk5:"5% Shoot UP",
    campaign_tatk5:"5% Tech UP",
    campaign_hppp5:"5% Tech UP",
    campaign_special5:"5% Special UP",
    satk:"S-ATK",
    ratk:"R-ATK",
    tatk:"T-ATK",
    sdef:"S-DEF",
    rdef:"R-DEF",
    tdef:"T-DEF",
    dex:"DEX",
    hp:"HP",
    pp:"PP",
    strikeResist:"Strike Resist",
    rangeResist:"Range Resist",
    techResist:"Tech Resist", 
    fireResist:"Fire Resist", 
    iceResist:"Ice Resist", 
    ltnResist:"Lightning Resist",
    windResist:"Wind Resist",
    lightResist:"Light Resist",
    darkResist:"Dark Resist"
}